      - name: Commit Risultati
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Aggiunge solo i file corretti
          git add Iscritti_Giovanili_In_Corso.json Iscritti_Open_In_Corso.json
          
          # Ignora il file temporaneo se esiste
          rm -f temp.pdf
          
          # Verifica se ci sono modifiche nei file specifici prima di fare commit
          if ! git diff --quiet --cached; then
            git commit -m "Aggiornamento iscritti in corso"
            git push
          else
            echo "Nessuna modifica rilevata nei file JSON."
          fi
