name: Tennis Bot Runner
on:
  workflow_dispatch: 

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install playwright pdfplumber
          playwright install chromium

      - name: Esecuzione Bot
        run: python bot.py

      - name: Upload dei risultati
        uses: actions/upload-artifact@v4
        with:
          name: risultati-partite
          path: |
            Giovanili.txt
            Open.txt
