name: Tennis Bot Extractor
on:
  workflow_dispatch: 

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install
        run: |
          pip install playwright pdfplumber
          playwright install chromium
      - name: Run Bot
        run: python bot.py
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: risultati-partite
          path: |
            Giovanili_Partite.txt
            Open_Partite.txt
